language: objective-c
osx_image: xcode7

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - XCODE_WORKSPACE=AlamofireObjectMapper.xcworkspace
  matrix:
    - SCHEME="AlamofireObjectMapper iOS" SDK="iphonesimulator"
    # - SCHEME="AlamofireObjectMapper OSX" SDK="macosx"

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script: 
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -workspace $XCODE_WORKSPACE -scheme "$SCHEME" -sdk "$SDK" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
  - xcodebuild -workspace $XCODE_WORKSPACE -scheme "$SCHEME" -sdk "$SDK" -configuration Release ONLY_ACTIVE_ARCH=NO test | xcpretty -c

notifications:
  email: false
